// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFRU1ogUpo04YnQvlu3xfvatWtZQLayQw',
    appId: '1:665815564201:web:628c891e7e26ffde4e4eb8',
    messagingSenderId: '665815564201',
    projectId: 'airportproject-93b9e',
    authDomain: 'airportproject-93b9e.firebaseapp.com',
    storageBucket: 'airportproject-93b9e.firebasestorage.app',
    measurementId: 'G-VPJBMFKR2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD50yH5Ok-pXk0Jij9vRSdrIiLpQXUCWbg',
    appId: '1:665815564201:android:502ee8084c9a7c034e4eb8',
    messagingSenderId: '665815564201',
    projectId: 'airportproject-93b9e',
    storageBucket: 'airportproject-93b9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACMWHyrbMc0XQJ9wG14J5TlpwQdZ7WfCY',
    appId: '1:665815564201:ios:d09bfc1b6a1aebe34e4eb8',
    messagingSenderId: '665815564201',
    projectId: 'airportproject-93b9e',
    storageBucket: 'airportproject-93b9e.firebasestorage.app',
    iosBundleId: 'com.example.auribisesTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACMWHyrbMc0XQJ9wG14J5TlpwQdZ7WfCY',
    appId: '1:665815564201:ios:d09bfc1b6a1aebe34e4eb8',
    messagingSenderId: '665815564201',
    projectId: 'airportproject-93b9e',
    storageBucket: 'airportproject-93b9e.firebasestorage.app',
    iosBundleId: 'com.example.auribisesTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFRU1ogUpo04YnQvlu3xfvatWtZQLayQw',
    appId: '1:665815564201:web:bb36e9f0c75c05934e4eb8',
    messagingSenderId: '665815564201',
    projectId: 'airportproject-93b9e',
    authDomain: 'airportproject-93b9e.firebaseapp.com',
    storageBucket: 'airportproject-93b9e.firebasestorage.app',
    measurementId: 'G-VGRBNG68WH',
  );
}
